# Copyright (C) CampusIoT,  - All Rights Reserved
# Written by CampusIoT Dev Team, 2016-2018

version: '2'
services:
    campusiot-app:
        image: campusiot
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://campusiot-mysql:3306/campusiot?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    campusiot-mysql:
        extends:
            file: mysql.yml
            service: campusiot-mysql

    campusiot-mosquitto:
        extends:
            file: mosquitto.yml
            service: mosquitto
